server:
  port: 8080

xiao7:
  redis:
    enable: true
  datasource:
    username: root
    password: 123456
    #mysql8版本以上的驱动包，需要指定以下时区
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    #mysql8版本以上指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #引入Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    multi[0]:
      name: bill
      username: root
      password: 123456
      #mysql8版本以上的驱动包，需要指定以下时区
      url: jdbc:mysql://localhost:3306/bill?serverTimezone=GMT%2B8&characterEncoding=utf-8
      #mysql8版本以上指定新的驱动类
      driver-class-name: com.mysql.cj.jdbc.Driver
      #引入Druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
  mybaits:
    enable-sql-log: true
spring:
  elasticsearch:
    rest:
      uris: http://101.37.30.142:9200
      username: elastic
      password: 123456
  redis:
    database: 0
    sentinel:
      master: redisgroup
      nodes: 101.37.30.142:7001,101.37.30.142:7002,101.37.30.142:7003
    password: 123456

